import json

# Define the base mapping: { "Standard Name": [List of variations] }
base_mapping = {
    "Python": ["python", "py", "pyton", "pythn", "python3", "python2", "py3", "py2", "pypi", "cpython", "ipython"],
    "Java": ["java", "java8", "java11", "java17", "jdk", "jre", "jvm", "j2ee", "jakarta ee", "java spring"],
    "JavaScript": ["javascript", "js", "java script", "jscript", "ecmascript", "es6", "es5", "js/ts", "vanilla js", "vnilla js"],
    "TypeScript": ["typescript", "ts", "type script", "typ-script", "tsc", "typescrpt", "ts/js"],
    "C#": ["c#", "csharp", "c sharp", "c-sharp", "charp", "cshrp", ".net", ".net core", "dotnet", "dotnetcore", "c# .net", "cshap"],
    "C++": ["c++", "cpp", "c plus plus", "cplusplus", "c++11", "c++14", "c++17", "c++20", "vc++"],
    "C": ["c language", "lang c", "ansi c", "embedded c", "c programming"],
    "Go": ["golang", "go", "go lang", "go-lang", "google go", "gopher"],
    "Rust": ["rust", "rustlang", "rust-lang", "cargo", "rustc"],
    "PHP": ["php", "php7", "php8", "php-fpm", "lamp", "lemp"],
    "Swift": ["swift", "swiftui", "swift-lang", "swift4", "swift5"],
    "Kotlin": ["kotlin", "kt", "kotln", "kotlin/jvm", "kotlin/native"],
    "Ruby": ["ruby", "rb", "rby", "mri"],
    "Scala": ["scala", "scalajs", "sbt"],
    "Dart": ["dart", "dartlang", "dart-lang"],
    "R": ["r programming", "r language", "r lang", "cran"],
    "Perl": ["perl", "pl", "perll"],
    "Lua": ["lua", "luajit"],
    "Haskell": ["haskell", "ghc"],
    "Elixir": ["elixir", "mix", "iex"],
    "Clojure": ["clojure", "clj", "cljs"],
    "Solidity": ["solidity", "sol", "smart contract"],
    "MATLAB": ["matlab", "mathworks"],
    "Fortran": ["fortran", "f90", "f77"],
    "COBOL": ["cobol"],
    "Bash": ["bash", "sh", "shell script", "shell scripting", "bash script", "zsh"],
    "PowerShell": ["powershell", "ps1", "pwsh"],
    "SQL": ["sql", "structured query language", "pl/sql", "t-sql"],
    "HTML5": ["html", "html5", "htm", "hypertext markup language", "html/css"],
    "CSS3": ["css", "css3", "cascading style sheets", "css/html", "flexbox", "grid"],
    "React": ["react", "reactjs", "react.js", "rct", "react hooks", "preact"],
    "Angular": ["angular", "ng", "angula", "angularjs", "angular.js", "angular2+", "angular 2", "angular 10", "angular 12", "angular 14"],
    "Vue.js": ["vue", "vuejs", "vue.js", "vue2", "vue3", "vuex", "vuetify"],
    "Svelte": ["svelte", "sveltekit", "svelt"],
    "Next.js": ["nextjs", "next.js", "next.js 13", "next.js 14", "next.js 12"],
    "Nuxt.js": ["nuxtjs", "nuxt.js", "nuxt"],
    "Gatsby": ["gatsby", "gatsbyjs"],
    "Remix": ["remix", "remix-run"],
    "Tailwind CSS": ["tailwind", "tailwindcss", "tailwind css", "tw css"],
    "Bootstrap": ["bootstrap", "bootstrap4", "bootstrap5", "btstrap"],
    "Sass": ["sass", "scss"],
    "Less": ["less"],
    "jQuery": ["jquery", "jq", "j-query"],
    "Redux": ["redux", "rtk", "redux-toolkit", "redux saga", "redux-thunk"],
    "MobX": ["mobx"],
    "Zustand": ["zustand"],
    "Vite": ["vite", "vitejs"],
    "Webpack": ["webpack", "wp", "web-pack"],
    "Babel": ["babel", "babeljs"],
    "Node.js": ["node", "nodejs", "node.js", "node-js", "nvm", "npm", "yarn", "pnpm"],
    "Express.js": ["express", "expressjs", "express.js"],
    "NestJS": ["nestjs", "nest.js", "nest js"],
    "Fastify": ["fastify"],
    "Django": ["django", "djng", "django-rest-framework", "drf"],
    "Flask": ["flask", "flsk"],
    "FastAPI": ["fastapi", "fast api", "fstapi"],
    "Spring Boot": ["spring", "springboot", "spring boot", "spring cloud", "spring mvc", "spring security"],
    "Hibernate": ["hibernate", "jpa", "orm"],
    "Laravel": ["laravel", "laravl", "lrvl", "eloquent"],
    "Symfony": ["symfony", "symfny"],
    "CodeIgniter": ["codeigniter", "ci", "code igniter"],
    "ASP.NET Core": ["asp.net", "asp net", "asp.net core", "aspnetcore", "asp.net web api", ".net core", "dotnetcore"],
    "ASP.NET MVC": ["mvc", "asp.net mvc", "aspnet mvc"],
    "Ruby on Rails": ["ruby on rails", "rails", "ror"],
    "Phoenix": ["phoenix", "phx"],
    "Gin": ["gin", "gin-gonic"],
    "Fiber": ["fiber", "go-fiber", "go fiber"],
    "Echo": ["echo", "echo-framework"],
    "WordPress": ["wordpress", "wp", "word press"],
    "Drupal": ["drupal"],
    "Magento": ["magento", "magento2"],
    "Shopify": ["shopify", "liquid"],
    "Flutter": ["flutter", "flutr", "flutter-sdk"],
    "React Native": ["react native", "rn", "react-native"],
    "Ionic": ["ionic", "ionic-framework"],
    "Xamarin": ["xamarin", "xamarin-forms"],
    "Android SDK": ["android", "android studio", "android-sdk", "android dev", "android-app"],
    "iOS SDK": ["ios", "ios-sdk", "ios dev", "ios-app", "xcode", "objective-c", "objc", "obj-c"],
    "PostgreSQL": ["postgresql", "postgres", "psql", "postgres sql", "postgre"],
    "MySQL": ["mysql", "my-sql", "mysql8"],
    "MariaDB": ["mariadb"],
    "Oracle Database": ["oracle", "oracle db", "oracle-sql", "pl-sql", "pl/sql", "oracle 11g", "oracle 12c", "oracle 19c"],
    "SQL Server": ["sql server", "mssql", "ms sql", "microsoft sql server", "sqlserver", "ssms"],
    "SQLite": ["sqlite", "sq lite"],
    "MongoDB": ["mongodb", "mongo", "mongo db", "mongoose"],
    "Redis": ["redis"],
    "Cassandra": ["cassandra"],
    "DynamoDB": ["dynamodb", "dynamo db"],
    "Firebase": ["firebase", "firestore"],
    "Neo4j": ["neo4j"],
    "Elasticsearch": ["elasticsearch", "elastic search", "elk"],
    "RabbitMQ": ["rabbitmq", "rabbit mq"],
    "Kafka": ["kafka", "apache kafka"],
    "AWS": ["aws", "amazon web services", "ec2", "s3", "lambda", "rds", "iam", "route53", "cloudfront"],
    "Azure": ["azure", "microsoft azure", "azure-devops"],
    "GCP": ["gcp", "google cloud", "google cloud platform", "firebase"],
    "Docker": ["docker", "dockerize", "docker-compose", "containerization"],
    "Kubernetes": ["kubernetes", "k8s", "kube", "kuber", "kubectl", "helm"],
    "Terraform": ["terraform", "tf", "isc"],
    "Ansible": ["ansible"],
    "Jenkins": ["jenkins", "jnkins"],
    "Git": ["git", "git-scm"],
    "GitHub": ["github", "gh"],
    "GitLab": ["gitlab"],
    "Bitbucket": ["bitbucket"],
    "GitHub Actions": ["github actions", "github-actions", "gha"],
    "Nginx": ["nginx", "ngnx"],
    "Apache": ["apache", "apache2"],
    "Linux": ["linux", "unix", "ubuntu", "centos", "debian", "redhat", "fedora", "linux kernel"],
    "TensorFlow": ["tensorflow", "tf", "tf.js"],
    "PyTorch": ["pytorch", "torch"],
    "Keras": ["keras"],
    "Scikit-learn": ["sklearn", "scikit-learn", "scikit"],
    "Pandas": ["pandas", "pndas"],
    "NumPy": ["numpy", "nmpy"],
    "Matplotlib": ["matplotlib"],
    "Seaborn": ["seaborn"],
    "Apache Spark": ["spark", "apache spark", "pyspark", "scala spark"],
    "Apache Hadoop": ["hadoop", "hdfs", "mapreduce"],
    "Tableau": ["tableau"],
    "Power BI": ["power bi", "pbi", "powerbi"],
    "NLP": ["nlp", "natural language processing", "spacy", "nltk", "bert", "gpt"],
    "Computer Vision": ["computer vision", "cv", "opencv"],
    "Deep Learning": ["deep learning", "dl", "neural networks", "cnn", "rnn", "lstm"],
    "REST API": ["rest", "restful", "rest api", "rest-api", "api rest"],
    "GraphQL": ["graphql", "gql"],
    "gRPC": ["grpc"],
    "Microservices": ["microservices", "micro-services", "msa"],
    "Agile": ["agile", "scrum", "kanban"],
    "Jira": ["jira", "atlassian"],
    "Selenium": ["selenium", "selenium webdriver"],
    "Cypress": ["cypress"],
    "Playwright": ["playwright"],
    "Postman": ["postman"],
    "Swagger": ["swagger", "openapi", "open-api"],
}

# Create final mapping: { "variation": "Standard Name" }
final_mapping = {}
for standard, variations in base_mapping.items():
    for var in variations:
        final_mapping[var.lower()] = standard

# Output as a formatted string for inclusion in Python code
output = "SKILL_MAPPING: Dict[str, str] = {\n"
for key in sorted(final_mapping.keys()):
    output += f'    "{key}": "{final_mapping[key]}",\n'
output += "}"

print(output)
print(f"\nTotal entries: {len(final_mapping)}")
print(f"Total categories: {len(base_mapping)}")
